services:
  squares.server:
    image: squares.server:dev
    build:
      context: .
      dockerfile: ./Squares.Server/Dockerfile
      target: dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ConnectionStrings__Development=${DEV_DB_CONNECTION_STRING}
    ports:
      - "8000:8080"
    volumes:
      - ./Squares.Server:/app/Squares.Server
      - ./Squares.Application:/app/Squares.Application
      - ./Squares.Domain:/app/Squares.Domain
      - ./Squares.Infrastructure:/app/Squares.Infrastructure
      - /app/Squares.Server/bin
      - /app/Squares.Server/obj
      - /app/Squares.Application/bin
      - /app/Squares.Application/obj
      - /app/Squares.Domain/bin
      - /app/Squares.Domain/obj
      - /app/Squares.Infrastructure/bin
      - /app/Squares.Infrastructure/obj
    networks:
      - app-network
    depends_on:
      - db
      
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: squares
      PGPORT: 5434
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app-network
    ports:
      - "5434:5434"

networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
  pgadmin_data: